filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    processors:
      - add_docker_metadata:
          host: "unix:///var/run/docker.sock"
      - decode_json_fields:
          fields: ["message"]
          target: "json"
          overwrite_keys: true
          add_error_key: true

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config:
        type: container
        paths:
          - /var/lib/docker/containers/${data.docker.container.id}/*.log

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "iot-logs-%{+yyyy.MM.dd}"
      when.contains:
        container.name: "iot-controller"
    - index: "iot-logs-%{+yyyy.MM.dd}"
      when.contains:
        container.name: "rule-engine"
    - index: "iot-logs-%{+yyyy.MM.dd}"
      when.contains:
        container.name: "data-simulator"
    - index: "filebeat-%{+yyyy.MM.dd}"

setup.kibana:
  host: "kibana:5601"

# Отключаем автоматическую загрузку дашбордов (Kibana медленно запускается)
setup.dashboards.enabled: false
setup.template.enabled: true
setup.template.name: "iot-logs"
setup.template.pattern: "iot-logs-*"
setup.ilm.enabled: false

logging.level: info
logging.to_files: false

